In [80]:
def xtime(x):
    return (x << 1) ^ (((x >> 7) & 0x01) * 0x1b) 
        
def gmult(x, y):
    result = (y & 0x01) * x
    result ^= (y>>1 & 0x01) * xtime(x)
    result ^= (y>>2 & 0x01) * xtime(xtime(x))
    result ^= (y>>3 & 0x01) * xtime(xtime(xtime(x)))
    result ^= (y>>4 & 0x01) * xtime(xtime(xtime(xtime(x))))
    return result & 0xff

def mix_columns(state):
    for row in range(4):
        # temporary variables
        a = state[row,0]
        b = state[row,1]
        c = state[row,2]
        d = state[row, 3]
        
        state[row, 0] = gmult(a, 2) ^ gmult(b, 3) ^ c ^ d
        state[row, 1] = a ^ gmult(b, 2) ^ gmult(c, 3) ^ d
        state[row, 2] = a ^ b ^ gmult(c, 2) ^ gmult(d, 3)
        state[row, 3] = gmult(a, 3) ^ b ^ c ^ gmult(d, 2)
    return state

In [77]:
aes = AES()
aes.state

matrix([[  6,   6,   6,   6],
        [210,  46, 141,  88],
        [221, 147,  68, 119],
        [100, 222,  70, 224]])

In [81]:
mix_columns(aes.state)

matrix([[  6,   6,   6,   6],
        [181, 237, 234, 155],
        [143,  46,  22, 202],
        [236,  38, 206,  24]])

In [1]:
import numpy as np
from block_cipher import AES

In [42]:
aes = AES()
aes.state.shape

(4, 4)

In [54]:
def mixColumns(a, b, c, d):
    printHex(gmul(a, 2) ^ gmul(b, 3) ^ gmul(c, 1) ^ gmul(d, 1))
    printHex(gmul(a, 1) ^ gmul(b, 2) ^ gmul(c, 3) ^ gmul(d, 1))
    printHex(gmul(a, 1) ^ gmul(b, 1) ^ gmul(c, 2) ^ gmul(d, 3))
    printHex(gmul(a, 3) ^ gmul(b, 1) ^ gmul(c, 1) ^ gmul(d, 2))
    print()

def gmul(a, b):
    if b == 1:
        return a
    tmp = (a << 1) & 0xff
    if b == 2:
        return tmp if a < 128 else tmp ^ 0x1b
    if b == 3:
        return gmul(a, 2) ^ a
def printHex(val):
    return print('{:02x}'.format(val), end=' ')

In [56]:
def mcm(X,Y):
    result=np.zeros((4,4),np.uint64)
    for i in range(len(X)):
    # iterate through columns of Y
      for j in range(Y.shape[1]):
        # iterate through rows of Y
        for k in range(len(Y)):
            result[i,j] = result[i,j] ^ (X[i,k] * Y[k,j])
    return result

In [ ]:
def substitution(x, y):
    return np.array(
            [
                self.substitution_lookup_table.reshape((256))[b]
                for b in np.nditer(self.state)
            ],
        ).reshape(self.state.shape)

In [58]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
result = [[0,0,0,0],
          [0,0,0,0],
          [0,0,0,0],
          [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
      # iterate through rows of Y
      for k in range(len(Y)):
         result[i][j] = result[i][j] ^ (X[i][k] * Y[k][j])
result

[[11, 22, 0, 0], [19, 50, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [55]:
mixColumns(0, 17, 34, 51)

22 77 00 55 


In [53]:
mcm = np.zeros(shape=(4,4), dtype=np.int64)
_starting_mcm = np.array([3,1,1,2])
for _ in range(len(_starting_mcm)):
    if _ == 0:
        mcm[_] = _starting_mcm
    else:
        mcm[_] = np.roll(mcm[_-1], shift =3)
    
mcm

array([[3, 1, 1, 2],
       [1, 1, 2, 3],
       [1, 2, 3, 1],
       [2, 3, 1, 1]], dtype=int64)

In [44]:
np.array(
    [sub_lookup.reshape((256))[b] for b in np.nditer(aes.state)]
    ).reshape(aes.state.shape)

array([[151,  76,   1, 230],
       [181, 237, 234, 155],
       [143,  46,  22, 202],
       [236,  38, 206,  24]])

In [41]:
for b in np.nditer(aes.state):
    print(sub_lookup.reshape((256))[b])

151
76
1
230
181
237
234
155
143
46
22
202
236
38
206
24


In [3]:
for r in range(len(aes.state)):
    aes.state[r] = np.roll(np.array(aes.state[r]), r)
aes.state

matrix([[151,  76,   1, 230],
        [181, 237, 234, 155],
        [143,  46,  22, 202],
        [236,  38, 206,  24]])

In [13]:
import numpy as np
np.bitwise_xor(aes.state[0], aes.state[-1])

matrix([[164, 179, 163,  60]], dtype=int32)

In [ ]:
aes.state

In [4]:
bytes_list = bytes("Ciao", encoding='utf-8')
for b in bytes_list:
    print(b)

67
105
97
111
