In [1]:
import numpy as np
from block_cipher import AES

In [10]:
aes = AES()
aes.state

matrix([[153, 148, 148, 189],
        [ 65, 204, 121,  27],
        [222, 108, 124, 232],
        [241, 115, 245,   3]])

In [15]:
aes.state = np.insert(aes.state, 0, aes.state[-1], axis = 0)

In [16]:
aes.state

matrix([[241, 115, 245,   3],
        [241, 115, 245,   3],
        [241, 115, 245,   3],
        [153, 148, 148, 189],
        [ 65, 204, 121,  27],
        [222, 108, 124, 232],
        [241, 115, 245,   3]])

In [18]:
n=4
aes.state[:-n]

matrix([[241, 115, 245,   3],
        [241, 115, 245,   3],
        [241, 115, 245,   3]])

In [19]:
len(aes.key)

4

In [20]:
aes.num_cols_key-len(aes.state)

AttributeError: 'AES' object has no attribute 'num_cols_key'

In [12]:
aes.key

matrix([[218,  15, 238,  98,  72, 175,  54, 219],
        [ 66,  50, 163, 120,  80,  36,  12, 217],
        [ 90, 190, 231, 190,  60, 120, 158,  63],
        [ 92, 183, 119, 236, 178, 153, 251, 204]])

In [13]:
import numpy as np
np.bitwise_xor(aes.state[0], aes.state[-1])

matrix([[164, 179, 163,  60]], dtype=int32)

In [ ]:
aes.state

In [4]:
bytes_list = bytes("Ciao", encoding='utf-8')
for b in bytes_list:
    print(b)

67
105
97
111
